#docker-compose permet de lier les 3 containers entre eux

version: '3'
services:


#---------------------NGINX------------------------#

  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress-data:/var/www/html #ou - wordpress-data:/var/www/wordpress ?
      # - nginx-data:/var/www/nginx #pourquoi pas des nom de volumes differents ? pour securiser 
    # image: nginx ATTENTION va chercher l image en ligne, forbidden !
    #Modifie le nom de l'adresse en ligne
    container_name: nginx
    restart: always
    ports:
      - "443:443" #port securise
      # - "80:80" #pour le test
    depends_on:
      - wordpress
      - mariadb
    networks:
      - my-network # network docker qui fait le lien entre les containers


#-------------------MARIADB---------------------#

  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
       - mariadb-data:/var/lib/mysql
      # - wordpress-data:/var/www/html #ou - wordpress-data:/var/www/wordpress ?
    container_name: mariadb
    restart: always
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 10s  # wait for mariadb to be ready
      retries: 4
      start_period: 10s
    env_file:
      - .env
    networks:
      - my-network


#-------------------WORDPRESS---------------------#

  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www/html #ou - wordpress-data:/var/www/wordpress ?
    container_name: wordpress
    restart: always # ou restart: on-failure
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - my-network

volumes:
  # wp-volume:
  #   driver: local
  # mariadb-data:
  wordpress-data:
  nginx-conf:

networks:
  my-network:
    driver: bridge