version: '3'
services:
  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my-network
    restart: always  # ou restart: on-failure

# ... autres services ...

networks:
  my-network:
    driver: bridge
