version: '3'
services:

  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - nginx-conf:/etc/nginx/conf.d
    image: nginx
    ports:
      - "443:443" #port securise
      # - "80:80" #pour le test
    # depends_on:
    #   - wordpress
    networks:
      - my-network

  mariadb:
    build:
      context: ./requirements/mariadb
    # volumes:
    #   - mariadb-data:/var/lib/mysql
    image: mariadb
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    args:
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - my-network

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #   volumes:
  #     - wordpress-data:/var/www/html
  #   image: wordpress
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - my-network

volumes:
  wp_volume:
    driver: local
  # mariadb-data:
  # wordpress-data:
  nginx-conf:

networks:
  my-network:
    driver: bridge