version: '3'
services:
  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - my-network
    restart: always  # ou restart: on-failure

# ... autres services ...

networks:
  my-network:
    driver: bridge
